USE [MIS_DB]
GO

CREATE TABLE [dbo].[FOX_TBL_SURVEY_AUTOMATION_SERVICE_LOG](
	[SURVEY_AUTOMATION_LOG_ID] [bigint] NOT NULL,
	[PATIENT_ACCOUNT] [bigint] NULL,
	[SURVEY_ID] [bigint] NULL,
	[FILE_NAME] [varchar](200) NULL,
	[PRACTICE_CODE] [bigint] NULL,
	[CREATED_DATE] [datetime] NULL,
	[CREATED_BY] [varchar](70) NULL,
	[MODIFIED_DATE] [datetime] NULL,
	[MODIFIED_BY] [varchar](70) NULL,
	[DELETED] [bit] NULL,
	[IS_SMS] [bit] NULL,
	[IS_EMAIL] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[SURVEY_AUTOMATION_LOG_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[FOX_TBL_SURVEY_AUTOMATION_SERVICE_LOG] ADD  DEFAULT (getdate()) FOR [CREATED_DATE]
GO

ALTER TABLE [dbo].[FOX_TBL_SURVEY_AUTOMATION_SERVICE_LOG] ADD  DEFAULT ('FOX_SERVICE') FOR [CREATED_BY]
GO

ALTER TABLE [dbo].[FOX_TBL_SURVEY_AUTOMATION_SERVICE_LOG] ADD  DEFAULT (getdate()) FOR [MODIFIED_DATE]
GO

ALTER TABLE [dbo].[FOX_TBL_SURVEY_AUTOMATION_SERVICE_LOG] ADD  DEFAULT ('FOX_SERVICE') FOR [MODIFIED_BY]
GO

ALTER TABLE [dbo].[FOX_TBL_SURVEY_AUTOMATION_SERVICE_LOG] ADD  DEFAULT ((0)) FOR [DELETED]
GO