--//CREATE TABLE [FOX_TBL_MFA_INVALID_USER_ATTEMPTS] //// --
CREATE TABLE [dbo].[FOX_TBL_MFA_INVALID_USER_ATTEMPTS](
	[INVALID_MFA_COUNT_ID] [bigint] NOT NULL,
	[USER_NAME] [varchar](1000) NULL,
	[FAIL_ATTEMPT_COUNT] [bigint] NULL,
	[CREATED_BY] [varchar](70) NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[MODIFIED_BY] [varchar](70) NOT NULL,
	[MODIFIED_DATE] [datetime] NOT NULL,
	[DELETED] [bit] NOT NULL,
	[LAST_ATTEMPT_DATE_UTC] [datetime] NULL,
	[SENT_OTP_COUNT] [bigint] NULL,
 CONSTRAINT [PK_FOX_TBL_MFA_INVALID_USER_ATTEMPTS] PRIMARY KEY CLUSTERED 
(
	[INVALID_MFA_COUNT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[FOX_TBL_MFA_INVALID_USER_ATTEMPTS] ADD  CONSTRAINT [DF_FOX_TBL_MFA_INVALID_USER_ATTEMPTS_CREATED_BY]  DEFAULT ('FOX TEAM') FOR [CREATED_BY]
GO

ALTER TABLE [dbo].[FOX_TBL_MFA_INVALID_USER_ATTEMPTS] ADD  CONSTRAINT [DF_FOX_TBL_MFA_INVALID_USER_ATTEMPTS_CREATED_DATE]  DEFAULT (getdate()) FOR [CREATED_DATE]
GO

ALTER TABLE [dbo].[FOX_TBL_MFA_INVALID_USER_ATTEMPTS] ADD  CONSTRAINT [DF_FOX_TBL_MFA_INVALID_USER_ATTEMPTS_MODIFIED_BY]  DEFAULT ('FOX TEAM') FOR [MODIFIED_BY]
GO

ALTER TABLE [dbo].[FOX_TBL_MFA_INVALID_USER_ATTEMPTS] ADD  CONSTRAINT [DF_FOX_TBL_MFA_INVALID_USER_ATTEMPTS_MODIFIED_DATE]  DEFAULT (getdate()) FOR [MODIFIED_DATE]
GO

ALTER TABLE [dbo].[FOX_TBL_MFA_INVALID_USER_ATTEMPTS] ADD  CONSTRAINT [DF_FOX_TBL_MFA_INVALID_USER_ATTEMPTS_DELETED]  DEFAULT ((0)) FOR [DELETED]
GO

ALTER TABLE [dbo].[FOX_TBL_MFA_INVALID_USER_ATTEMPTS] ADD  DEFAULT ((0)) FOR [SENT_OTP_COUNT]
GO