--------------------------------------------------------
----- Folder Name: DevScripts > TableModifications
----- File Name: TableModifications.sql	
----- Created By: Muhammad Arslan Tufail
----- Created Date: 08/25/2022
----- Modified By: Muhammad Taseer Iqbal
----- Modified Date: 1/11/2023
--------------------------------------------------------

--------------------------------------------------------
----- JIRA ID: FOX-6593
----- Task Name: Item P504 | Quality Assurance Scoring Enhancements - development
----- Assignee: Muhammad Taseer Iqbal
----  Non Replication Table
--------------------------------------------------------

ALTER TABLE FOX_TBL_SURVEY_AUDIT_SCORES
ADD  APPROPRIATE_GREETING BIGINT
,APPROPRIATE_GREETING_TOTAL BIGINT
,TONE_OF_PATIENT BIGINT
,TONE_OF_PATIENT_TOTAL BIGINT
,COMPASSION_AND_EMPATHY BIGINT
,COMPASSION_AND_EMPATHY_TOTAL BIGINT
,GRAMMAR_AND_PRONUNCIATION BIGINT
,GRAMMAR_AND_PRONUNCIATION_TOTAL BIGINT
,PATIENT_IDENTITY BIGINT
,PATIENT_IDENTITY_TOTAL BIGINT
,ANSWER_PATIENT_QUESTIONS BIGINT
,ANSWER_PATIENT_QUESTIONS_TOTAL BIGINT
,STRONG_PRODUCT_KNOWLEDGE BIGINT
,STRONG_PRODUCT_KNOWLEDGE_TOTAL BIGINT
,COMMUNICATE_INFORMATION BIGINT
,COMMUNICATE_INFORMATION_TOTAL BIGINT
,DOCUMENTATION_COMPLETED_COMMUNICATED BIGINT
,DOCUMENTATION_COMPLETED_COMMUNICATED_TOTAL BIGINT
,APPROPRIATE_CLOSING BIGINT
,APPROPRIATE_CLOSING_TOTAL BIGINT;
GO

--------------------------------------------------------
----- JIRA ID: FOX-6993
----- Task Name: QAR Perform an Audit - Issues - development
----- Assignee: Muhammad Taseer Iqbal
----  Non Replication Table
--------------------------------------------------------

	ALTER TABLE FOX_TBL_SURVEY_AUDIT_SCORES ALTER COLUMN CLIENT_EXPERIENCE_COMMENT VARCHAR(1000)
	GO
	ALTER TABLE FOX_TBL_SURVEY_AUDIT_SCORES ALTER COLUMN SYSTEM_PROCESS_COMMENT VARCHAR(1000)
	GO
	ALTER TABLE FOX_TBL_SURVEY_AUDIT_SCORES ALTER COLUMN WOW_FACTOR_COMMENT VARCHAR(1000)
	GO
--------------------------------------------------------
----- JIRA ID: FOX-6872
----- Task Name: Item P522 | Alert Window Upon Login
----- Assignee: Muhammad Salman
----  Non Replication Table
--------------------------------------------------------
CREATE TABLE [dbo].[FOX_TBL_ANNOUNCEMENT_ROLE](
	[ANNOUNCEMENT_ROLE_ID] [bigint] NOT NULL,
	[ROLE_ID] [bigint] NULL,
	[ROLE_NAME] [varchar](50) NULL,
	[ANNOUNCEMENT_ID] [bigint] NULL,
	[PRACTICE_CODE] [bigint] NULL,
	[CREATED_DATE] [datetime] NULL,
	[CREATED_BY] [varchar](70) NULL,
	[MODIFIED_DATE] [datetime] NULL,
	[MODIFIED_BY] [varchar](70) NULL,
	[DELETED] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[ANNOUNCEMENT_ROLE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[FOX_TBL_ANNOUNCEMENT_ROLE] ADD  DEFAULT (getdate()) FOR [CREATED_DATE]
GO

ALTER TABLE [dbo].[FOX_TBL_ANNOUNCEMENT_ROLE] ADD  DEFAULT ('FOX_TEAM') FOR [CREATED_BY]
GO

ALTER TABLE [dbo].[FOX_TBL_ANNOUNCEMENT_ROLE] ADD  DEFAULT (getdate()) FOR [MODIFIED_DATE]
GO

ALTER TABLE [dbo].[FOX_TBL_ANNOUNCEMENT_ROLE] ADD  DEFAULT ('FOX_TEAM') FOR [MODIFIED_BY]
GO

ALTER TABLE [dbo].[FOX_TBL_ANNOUNCEMENT_ROLE] ADD  DEFAULT ('0') FOR [DELETED]
GO

--------------------------------------------------------
----- JIRA ID: FOX-6872
----- Task Name: Item P522 | Alert Window Upon Login
----- Assignee: Muhammad Salman
----  Non Replication Table
--------------------------------------------------------
CREATE TABLE [dbo].[FOX_TBL_ANNOUNCEMENT_HISTORY](
	[ANNOUNCEMENT_HISTORY_ID] [bigint] NOT NULL,
	[ANNOUNCEMENT_ID] [bigint] NULL,
	[USER_ID] [bigint] NULL,
	[USER_NAME] [varchar](50) NULL,
	[SHOW_COUNT] [int] NULL,
	[PRACTICE_CODE] [bigint] NULL,
	[CREATED_DATE] [datetime] NULL,
	[CREATED_BY] [varchar](70) NULL,
	[MODIFIED_DATE] [datetime] NULL,
	[MODIFIED_BY] [varchar](70) NULL,
	[DELETED] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[ANNOUNCEMENT_HISTORY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[FOX_TBL_ANNOUNCEMENT_HISTORY] ADD  DEFAULT (getdate()) FOR [CREATED_DATE]
GO

ALTER TABLE [dbo].[FOX_TBL_ANNOUNCEMENT_HISTORY] ADD  DEFAULT ('FOX_TEAM') FOR [CREATED_BY]
GO

ALTER TABLE [dbo].[FOX_TBL_ANNOUNCEMENT_HISTORY] ADD  DEFAULT (getdate()) FOR [MODIFIED_DATE]
GO

ALTER TABLE [dbo].[FOX_TBL_ANNOUNCEMENT_HISTORY] ADD  DEFAULT ('FOX_TEAM') FOR [MODIFIED_BY]
GO

ALTER TABLE [dbo].[FOX_TBL_ANNOUNCEMENT_HISTORY] ADD  DEFAULT ('0') FOR [DELETED]
GO
--------------------------------------------------------
----- JIRA ID: FOX-6872
----- Task Name: Item P522 | Alert Window Upon Login
----- Assignee: Muhammad Salman
----  Non Replication Table
--------------------------------------------------------
CREATE TABLE [dbo].[FOX_TBL_ANNOUNCEMENT](
	[ANNOUNCEMENT_ID] [bigint] NOT NULL,
	[ANNOUNCEMENT_DATE_FROM] [datetime] NULL,
	[ANNOUNCEMENT_DATE_TO] [datetime] NULL,
	[ANNOUNCEMENT_TITLE] [varchar](100) NULL,
	[ANNOUNCEMENT_DETAILS] [varchar](max) NULL,
	[PRACTICE_CODE] [bigint] NULL,
	[CREATED_DATE] [datetime] NULL,
	[CREATED_BY] [varchar](70) NULL,
	[MODIFIED_DATE] [datetime] NULL,
	[MODIFIED_BY] [varchar](70) NULL,
	[DELETED] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[ANNOUNCEMENT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[FOX_TBL_ANNOUNCEMENT] ADD  DEFAULT (getdate()) FOR [CREATED_DATE]
GO

ALTER TABLE [dbo].[FOX_TBL_ANNOUNCEMENT] ADD  DEFAULT ('FOX_TEAM') FOR [CREATED_BY]
GO

ALTER TABLE [dbo].[FOX_TBL_ANNOUNCEMENT] ADD  DEFAULT (getdate()) FOR [MODIFIED_DATE]
GO

ALTER TABLE [dbo].[FOX_TBL_ANNOUNCEMENT] ADD  DEFAULT ('FOX_TEAM') FOR [MODIFIED_BY]
GO

ALTER TABLE [dbo].[FOX_TBL_ANNOUNCEMENT] ADD  DEFAULT ('0') FOR [DELETED]
GO
--------------------------------------------------------
----- JIRA ID: FOX-6595
----- Task Name: Item P512 | Knowledge Base/ FAQs in Patient Helpdesk
----- Assignee: Muhammad Salman
----  Non Replication Table
--------------------------------------------------------

/****** Object:  Table [dbo].[FOX_TBL_PHD_FAQS_DETAILS]    Script Date: 10/29/2022 12:37:57 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[FOX_TBL_PHD_FAQS_DETAILS](
	[FAQS_ID] [bigint] NOT NULL,
	[QUESTIONS] [varchar](250) NULL,
	[ANSWERS] [nvarchar](max) NULL,
	[PRACTICE_CODE] [bigint] NOT NULL,
	[CREATED_DATE] [datetime] NULL,
	[CREATED_BY] [varchar](70) NULL,
	[MODIFIED_DATE] [datetime] NULL,
	[MODIFIED_BY] [varchar](70) NULL,
	[DELETED] [bit] NOT NULL,
 CONSTRAINT [PK_FOX_TBL_PHD_FAQS_DETAILS] PRIMARY KEY CLUSTERED 
(
	[FAQS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[FOX_TBL_PHD_FAQS_DETAILS] ADD  CONSTRAINT [DF_FOX_TBL_PHD_FAQS_DETAILS_CREATED_DATE]  DEFAULT (getdate()) FOR [CREATED_DATE]
GO

ALTER TABLE [dbo].[FOX_TBL_PHD_FAQS_DETAILS] ADD  CONSTRAINT [DF_FOX_TBL_PHD_FAQS_DETAILS_CREATED_BY]  DEFAULT ('FOX_TEAM') FOR [CREATED_BY]
GO

ALTER TABLE [dbo].[FOX_TBL_PHD_FAQS_DETAILS] ADD  CONSTRAINT [DF_FOX_TBL_PHD_FAQS_DETAILS_MODIFIED_DATE]  DEFAULT (getdate()) FOR [MODIFIED_DATE]
GO

ALTER TABLE [dbo].[FOX_TBL_PHD_FAQS_DETAILS] ADD  CONSTRAINT [DF_FOX_TBL_PHD_FAQS_DETAILS_MODIFIED_BY]  DEFAULT ('FOX_TEAM') FOR [MODIFIED_BY]
GO

ALTER TABLE [dbo].[FOX_TBL_PHD_FAQS_DETAILS] ADD  CONSTRAINT [DF_FOX_TBL_PHD_FAQS_DETAILS_DELETED]  DEFAULT ('0') FOR [DELETED]
GO
--------------------------------------------------------
----- JIRA ID: FOX-7285
----- Task Name: Item P1000 | Frictionless Referral Submission & Tracking (Referral Source & 3rd Party) - Carey's Feedback
----- Assignee: Muhammad Taseer Iqbal
----  Non Replication Table
--------------------------------------------------------
CREATE TABLE [dbo].[FOX_TBL_FRICTIONLESS_WORK_QUEUE_FILE_ALL](
	[FRICTIONLESS_REFERRAL_FILE_ID] [bigint] NOT NULL,
	[UNIQUE_ID] [varchar](50) NULL,
	[FILE_PATH] [varchar](500) NULL,
	[FILE_PATH1] [varchar](500) NULL,
	[WORK_ID] [bigint] NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[CREATED_BY] [varchar](70) NOT NULL,
	[MODIFIED_DATE] [datetime] NOT NULL,
	[MODIFIED_BY] [varchar](70) NOT NULL,
	[DELETED] [bit] NOT NULL,
	[PRACTICE_CODE] [bigint] NULL,
 CONSTRAINT [PK_FOX_TBL_FRICTIONLESS_WORK_QUEUE_FILE_ALL] PRIMARY KEY CLUSTERED 
(
	[FRICTIONLESS_REFERRAL_FILE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[FOX_TBL_FRICTIONLESS_WORK_QUEUE_FILE_ALL] ADD  CONSTRAINT [DF_FOX_TBL_FRICTIONLESS_WORK_QUEUE_FILE_ALL_CREATED_DATE]  DEFAULT (getdate()) FOR [CREATED_DATE]
GO

ALTER TABLE [dbo].[FOX_TBL_FRICTIONLESS_WORK_QUEUE_FILE_ALL] ADD  CONSTRAINT [DF_FOX_TBL_FRICTIONLESS_WORK_QUEUE_FILE_ALL_CREATED_BY]  DEFAULT ('FOX_TEAM') FOR [CREATED_BY]
GO

ALTER TABLE [dbo].[FOX_TBL_FRICTIONLESS_WORK_QUEUE_FILE_ALL] ADD  CONSTRAINT [DF_FOX_TBL_FRICTIONLESS_WORK_QUEUE_FILE_ALL_MODIFIED_DATE]  DEFAULT (getdate()) FOR [MODIFIED_DATE]
GO

ALTER TABLE [dbo].[FOX_TBL_FRICTIONLESS_WORK_QUEUE_FILE_ALL] ADD  CONSTRAINT [DF_FOX_TBL_FRICTIONLESS_WORK_QUEUE_FILE_ALL_MODIFIED_BY]  DEFAULT ('FOX_TEAM') FOR [MODIFIED_BY]
GO

ALTER TABLE [dbo].[FOX_TBL_FRICTIONLESS_WORK_QUEUE_FILE_ALL] ADD  CONSTRAINT [DF_FOX_TBL_FRICTIONLESS_WORK_QUEUE_FILE_ALL_DELETED]  DEFAULT ((0)) FOR [DELETED]
GO
--------------------------------------------------------
----- JIRA ID: FOX-7285
----- Task Name: Item P1000 | Frictionless Referral Submission & Tracking (Referral Source & 3rd Party) - Carey's Feedback
----- Assignee: Muhammad Taseer Iqbal
----  Non Replication Table
--------------------------------------------------------
CREATE TABLE [dbo].[FOX_TBL_FRICTIONLESS_REFERRAL](
	[FRICTIONLESS_REFERRAL_ID] [bigint] NOT NULL,
	[USER_TYPE] [varchar](50) NULL,
	[IS_SIGNED_REFERRAL] [bit] NULL,
	[SUBMITER_FIRST_NAME] [varchar](50) NULL,
	[SUBMITTER_LAST_NAME] [varchar](50) NULL,
	[SUBMITTER_PHONE] [varchar](10) NULL,
	[SUBMITTER_EMAIL] [varchar](50) NULL,
	[PROVIDER_NPI] [varchar](50) NULL,
	[PROVIDER_FIRST_NAME] [varchar](50) NULL,
	[PROVIDER_LAST_NAME] [varchar](50) NULL,
	[PROVIDER_ADDRESS] [varchar](500) NULL,
	[PROVIDER_CITY] [varchar](50) NULL,
	[PROVIDER_STATE] [varchar](2) NULL,
	[PROVIDER_TAXONOMY_DESC] [varchar](100) NULL,
	[PROVIDER_ZIP_CODE] [varchar](9) NULL,
	[PROVIDER_REGION] [varchar](50) NULL,
	[PROVIDER_REGION_CODE] [varchar](10) NULL,
	[PROVIDER_FAX] [varchar](10) NULL,
	[PROVIDER_PHONE_NO] [varchar](10) NULL,
	[PATIENT_FIRST_NAME] [varchar](50) NULL,
	[PATIENT_LAST_NAME] [varchar](50) NULL,
	[PATIENT_DOB] [datetime] NULL,
	[PATIENT_MOBILE_NO] [varchar](10) NULL,
	[PATIENT_EMAIL] [varchar](50) NULL,
	[PATIENT_SUBSCRIBER_ID] [varchar](25) NULL,
	[PATIENT_INSURANCE_PAYER_ID] [varchar](10) NULL,
	[IS_CHECK_ELIGIBILITY] [bit] NULL,
	[PATIENT_DISCIPLINE_ID] [varchar](50) NULL,
	[PATIENT_REFERRAL_NOTES] [varchar](500) NULL,
	[WORK_ID] [bigint] NULL,
	[PRACTICE_CODE] [bigint] NULL,
	[CREATED_DATE] [datetime] NULL,
	[CREATED_BY] [varchar](70) NULL,
	[MODIFIED_DATE] [datetime] NULL,
	[MODIFIED_BY] [varchar](70) NULL,
	[DELETED] [bit] NULL,
 CONSTRAINT [PK__FOX_TBL___BC96F500A761BB87] PRIMARY KEY CLUSTERED 
(
	[FRICTIONLESS_REFERRAL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[FOX_TBL_FRICTIONLESS_REFERRAL] ADD  CONSTRAINT [DF__FOX_TBL_F__CREAT__3FDCB949]  DEFAULT (getdate()) FOR [CREATED_DATE]
GO

ALTER TABLE [dbo].[FOX_TBL_FRICTIONLESS_REFERRAL] ADD  CONSTRAINT [DF__FOX_TBL_F__CREAT__40D0DD82]  DEFAULT ('FOX_TEAM') FOR [CREATED_BY]
GO

ALTER TABLE [dbo].[FOX_TBL_FRICTIONLESS_REFERRAL] ADD  CONSTRAINT [DF__FOX_TBL_F__MODIF__41C501BB]  DEFAULT (getdate()) FOR [MODIFIED_DATE]
GO

ALTER TABLE [dbo].[FOX_TBL_FRICTIONLESS_REFERRAL] ADD  CONSTRAINT [DF__FOX_TBL_F__MODIF__42B925F4]  DEFAULT ('FOX_TEAM') FOR [MODIFIED_BY]
GO

ALTER TABLE [dbo].[FOX_TBL_FRICTIONLESS_REFERRAL] ADD  CONSTRAINT [DF__FOX_TBL_F__DELET__43AD4A2D]  DEFAULT ((0)) FOR [DELETED]
GO


ALTER TABLE FOX_TBL_PATIENT_SURVEY ADD [PATIENT_WORK_NUMBER] VARCHAR(50), [PATIENT_CELL_NUMBER] VARCHAR(20);
GO


-------------------------------------------------------Sprint 24 Modifications--------------------------------------------------------------------------------


ALTER Table FOX_TBL_FRICTIONLESS_SERVICE_UNAVAILABLE_ZIPCODE
ADD ADDRESS varchar(500) null 


ALTER Table FOX_TBL_FRICTIONLESS_SERVICE_UNAVAILABLE_ZIPCODE
ADD FRICTIONLESS_REFERRAL_ID BIGINT null 


ALTER Table FOX_TBL_FRICTIONLESS_SERVICE_UNAVAILABLE_ZIPCODE
ADD STATE varchar(2) null 




ALTER Table FOX_TBL_FRICTIONLESS_REFERRAL
ADD PATIENT_ZIP_CODE varchar(9) null 


ALTER Table FOX_TBL_FRICTIONLESS_REFERRAL
ADD PATIENT_CITY_NAME varchar(50) null 


ALTER Table FOX_TBL_FRICTIONLESS_REFERRAL
ADD PATIENT_STATE varchar(2) null 


ALTER Table FOX_TBL_FRICTIONLESS_REFERRAL
ADD PATIENT_ADDRESS varchar(500) null 