IF (OBJECT_ID('FOX_PROC_GET_PATIENT_SURVEY_LIST') IS NOT NULL ) DROP PROCEDURE FOX_PROC_GET_PATIENT_SURVEY_LIST  
GO
CREATE PROCEDURE [dbo].[FOX_PROC_GET_PATIENT_SURVEY_LIST] -- 1012714, 10127145639211, 0
	@PRACTICE_CODE BIGINT
	,@PATIENT_ACCOUNT BIGINT
	,@IS_SURVEYED INT
AS
BEGIN
	DECLARE @SURVEY_STATUS BIT; 
	IF ( @IS_SURVEYED = 1)
        BEGIN 
            SET @SURVEY_STATUS = 1;
        END
	ELSE
		BEGIN 
            SET @SURVEY_STATUS = 0;
        END
	
	SELECT	DISTINCT PS.PATIENT_ACCOUNT_NUMBER,ISNULL(PS.PATIENT_MIDDLE_INITIAL,'') AS PATIENT_MIDDLE_INITIAL,PS.*,
	                CONVERT(INT,ROUND(DATEDIFF(HOUR,PS.PATIENT_DATE_OF_BIRTH,GETDATE())/8766.0,0)) AS PATIENT_AGE,
					 CONVERT(INT,ROUND(DATEDIFF(HOUR,PS.RESPONSIBLE_PARTY_DATE_OF_BIRTH,GETDATE())/8766.0,0)) AS RESPONSIBLE_PARTY_AGE,
					 AU.FIRST_NAME AS SURVEYED_BY_FNAME, 
					 AU.LAST_NAME AS SURVEYED_BY_LNAME, 
					 ISNULL(PS.SURVEY_STATUS_CHILD, '') AS SURVEY_STATUS_CHILD,
					 PS.SURVEY_FORMAT_TYPE

	FROM FOX_TBL_PATIENT_SURVEY PS
		 LEFT JOIN FOX_TBL_APPLICATION_USER AU ON AU.USER_NAME = PS.MODIFIED_BY

	WHERE	ISNULL(PS.DELETED, 0) = 0 
	        AND PS.PRACTICE_CODE = @PRACTICE_CODE
			AND IS_SURVEYED = @SURVEY_STATUS
			AND PS.PATIENT_ACCOUNT_NUMBER = @PATIENT_ACCOUNT
END

