IF (OBJECT_ID('FOX_PROC_GET_FEEDBACK_CALLER_LIST') IS NOT NULL ) DROP PROCEDURE FOX_PROC_GET_FEEDBACK_CALLER_LIST 
GO  
-- AUTHOR:  <DEVELOPER, ABDUR RAFAY>        
-- CREATE DATE: <CREATE DATE, 26/04/2018>        
-- DESCRIPTION: <GET FEEDBACK CALLER_ LIST>        
        
-- EXEC FOX_PROC_GET_FEEDBACK_CALLER_LIST_USAMA 1011163,54410118        
        
CREATE PROCEDURE [dbo].[FOX_PROC_GET_FEEDBACK_CALLER_LIST] -- 1012714, 103       
  @PRACTICE_CODE BIGINT,        
  @ROLE_ID BIGINT        
         
AS        
BEGIN        
        
        
 SELECT USER_NAME, (FIRST_NAME + ' '+ LAST_NAME) AS NAME, EMAIL      
 FROM FOX_TBL_APPLICATION_USER        
 WHERE        
      ROLE_ID = @ROLE_ID         
      AND ISNULL(DELETED, 0) = 0        
   AND PRACTICE_CODE = @PRACTICE_CODE        
   UNION         
          
   SELECT  DISTINCT phd.CREATED_BY AS USER_NAME, (AU.FIRST_NAME + ' '+ AU.LAST_NAME) AS NAME , EMAIL      
   FROM FOX_TBL_PHD_CALL_DETAILS phd        
   left JOIN FOX_TBL_APPLICATION_USER  as AU on  phd.CREATED_BY = AU.USER_NAME AND AU.PRACTICE_CODE = @PRACTICE_CODE         
   WHERE        
      ISNULL(phd.DELETED, 0) = 0        
   AND phd.PRACTICE_CODE = @PRACTICE_CODE    
    AND ISNULL(AU.DELETED,0)= 0        
          
 ORDER BY NAME ASC        
END 
