-- =============================================          
-- Author:  <AFTAB KHAN>          
-- Create date: <07/12/2023>          
-- Description: <FOX_PROC_SET_MFA_INVALID_LOGIN_ATTEMPTS>          
-- =============================================          
-- FOX_PROC_SET_MFA_INVALID_LOGIN_ATTEMPTS 'aftabkhan@carecloud.com'          
CREATE PROCEDURE FOX_PROC_SET_MFA_INVALID_LOGIN_ATTEMPTS           
 -- Add the parameters for the stored procedure here          
 @USER_NAME NVARCHAR(100),  
 @LAST_ATTEMPTUTC_DATETIME DATETIME  
AS          
BEGIN          
 DECLARE @MAX_ID BIGINT          
 SET @MAX_ID = (SELECT ISNULL(MAX(INVALID_USER_COUNT_ID), 500100) FROM FOX_TBL_INVALID_USER_ATTEMPTS)                   
 IF EXISTS(SELECT * FROM FOX_TBL_MFA_INVALID_USER_ATTEMPTS with (nolock) WHERE USER_NAME = @USER_NAME)          
 BEGIN          
  UPDATE FOX_TBL_MFA_INVALID_USER_ATTEMPTS          
   SET FAIL_ATTEMPT_COUNT = FAIL_ATTEMPT_COUNT + 1,          
   MODIFIED_DATE = GETDATE(),  
   LAST_ATTEMPT_DATE_UTC = @LAST_ATTEMPTUTC_DATETIME  
  WHERE USER_NAME = @USER_NAME                  
  SELECT FAIL_ATTEMPT_COUNT FROM FOX_TBL_MFA_INVALID_USER_ATTEMPTS with (nolock) WHERE USER_NAME = @USER_NAME          
 END          
 ELSE          
 BEGIN          
  INSERT INTO FOX_TBL_MFA_INVALID_USER_ATTEMPTS(INVALID_MFA_COUNT_ID,USER_NAME,FAIL_ATTEMPT_COUNT, CREATED_DATE, MODIFIED_DATE, LAST_ATTEMPT_DATE_UTC)          
  VALUES(@MAX_ID + 1, @USER_NAME, 1, GETDATE(), GETDATE(), @LAST_ATTEMPTUTC_DATETIME)                 
  SELECT FAIL_ATTEMPT_COUNT FROM FOX_TBL_MFA_INVALID_USER_ATTEMPTS with (nolock)  WHERE INVALID_MFA_COUNT_ID = @MAX_ID          
          
 END          
          
END 
