--EXEC FOX_PROC_GET_FAIL_COUNT_FOR_MFA_USER 'aftabkhan@carecloud.com'      
CREATE PROCEDURE [dbo].[FOX_PROC_GET_FAIL_COUNT_FOR_MFA_USER]      
(      
    @USER_NAME VARCHAR(1000)      
)      
AS      
BEGIN    
  
        
   SELECT MI.SENT_OTP_COUNT, MI.INVALID_MFA_COUNT_ID, AU.EMAIL, AU.USER_NAME,  MI.USER_NAME, MI.FAIL_ATTEMPT_COUNT, MI.CREATED_DATE, MI.MODIFIED_DATE, MI.LAST_ATTEMPT_DATE_UTC    
FROM FOX_TBL_APPLICATION_USER AU with (nolock)    
inner JOIN FOX_TBL_MFA_INVALID_USER_ATTEMPTS MI ON AU.EMAIL = MI.USER_NAME    
WHERE (AU.USER_NAME = @USER_NAME OR MI.USER_NAME = '' OR AU.EMAIL = @USER_NAME)    
     
END    
